sonar.projectKey=EPLATFORM-SEPFE
sonar.projectName=SEP FRONT END DEVELOP
sonar.projectVersion=4.12.0-SNAPSHOT
sonar.sources=src/app
sonar.test=src/app
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/*.module.ts,**/*.model*.ts,**/*.mock*.ts,**/index.ts,**/test-functionality/**,**/**.spec.util.ts,**/**.spec.utils.ts
sonar.cpd.exclusions=**/app/test/**.*
sonar.coverage.exclusions=**/app/test/**.*
sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPaths=src/coverage/lcov/lcov.info
