export enum UserRolesEnum {
    REPORTER = 'REPORTER',
    SUPERVISOR = 'SUPERVISOR',
    ADMINISTRATOR = 'ADMINISTRATOR',
    VALIDATOR = 'VALIDATOR',
    COORDINATOR = 'COORDINATOR',
    SEP_APP_ROLE = 'SEP_APP_ROLE'
}
